version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  relay: pipes

# serve static files
static:
  dir: "public"

http:
  address: 0.0.0.0:8080
  middleware: [ "gzip", "static", "headers" ]
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: 16
    supervisor:
      max_worker_memory: 100
      watch_tick: 5s

jobs:
  consume: [ ]
  pool:
    num_workers: 2
    supervisor:
      max_worker_memory: 100

metrics:
  address: localhost:2112
