version: "3.7"

services:
  php:
    container_name: keeper
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3394:3306 # 3394 on host system
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keeper
      - MYSQL_USER=keeper
      - MYSQL_PASSWORD=root
      - TZ=US/Eastern

  nginx:
    container_name: keeper-nginx
    ports:
      - 8080:80
    depends_on:
      - php
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    command: "./wait-for-it.sh php:8080 -- nginx -g 'daemon off;'"
