version: "3.7"

services:
  php:
    volumes:
      - ./app:/var/www/app
      - ./runtime:/var/www/runtime
      - ./composer.json:/var/www/composer.json
      - ./.env:/var/www/.env
    env_file:
      - .env
    command: "/var/server/rr serve -d -o http.pool.num_workers=1 -o http.pool.debug=true -o jobs.pool.num_workers=1"
